import './build-installers.mjs';
import {build} from 'esbuild';
import {writeFile,readFile} from 'node:fs/promises';
const result=await build({entryPoints:['src/browser/account.js'],bundle:true,minify:true,format:'iife',target:'es2022',write:false,legalComments:'inline'});
await writeFile('src/account-bundle.ts','// Generated by pnpm run browser. Do not edit.\nexport const accountScript = '+JSON.stringify(result.outputFiles[0].text)+';\n');

await writeFile('src/terminal-style.ts','// Generated.\n'+'export const terminalStyle = '+JSON.stringify(await readFile('node_modules/@xterm/xterm/css/xterm.css','utf8'))+';\n');
