const el=(tag,cls,value)=>{const e=document.createElement(tag);e.className=cls;if(value!==undefined)e.textContent=value;return e;};
export const bytes=n=>{if(n===undefined||n===null||!Number.isFinite(n))return '未知';if(n===0)return '0 B';const i=Math.min(4,Math.floor(Math.log(n)/Math.log(1024)));return (n/1024**i).toFixed(i?1:0)+' '+['B','KiB','MiB','GiB','TiB'][i];};
export function storageKind(d){if(d.kind==='disk'){if(/^\/dev\/(zram|ram)\d+$/.test(d.id))return 'memory-device';if(/^\/dev\/mmcblk\d+boot\d+$/.test(d.id))return 'boot-region';if(/^\/dev\/nbd\d+$/.test(d.id)&&!d.total)return 'disconnected';}return d.kind;}
export function freeSpace(h){
 const disks=h?.disks||[],containers=disks.filter(d=>d.kind==='container'&&d.free!==undefined),seen=new Set(),records=[];
 for(const d of disks){if(d.free===undefined||!Number.isFinite(d.free)||['memory-device','boot-region','disconnected'].includes(storageKind(d)))continue;if(d.kind!=='container'&&containers.some(c=>d.parent===c.id||d.id.startsWith(c.id+'s')))continue;if(seen.has(d.id))continue;seen.add(d.id);records.push(d);}
 return {known:records.length,free:records.reduce((n,d)=>n+d.free,0),total:records.reduce((n,d)=>n+(d.total||0),0)};
}
const kinds={'memory-device':'内存块设备','boot-region':'eMMC 启动区',disconnected:'未连接块设备',disk:'物理 / 虚拟磁盘',partition:'分区',volume:'卷',container:'共享容器',lvm:'LVM',crypt:'加密映射',raid1:'RAID 1',raid0:'RAID 0',raid5:'RAID 5',raid6:'RAID 6',raid10:'RAID 10',mpath:'多路径'};
export function hardwareCells(h,platform,label,locked=false){
 const unknown=locked?'解锁查看':'未检测',system=el('td','hardware-cell'),cpu=el('td','hardware-cell'),memory=el('td','hardware-cell'),disks=el('td','hardware-cell');
 system.append(el('div','hardware-primary',h?.os||({macos:'macOS',darwin:'macOS',linux:'Linux',windows:'Windows'}[platform])||unknown),el('div','sub',h?.arch||''));
 cpu.append(el('div','hardware-primary',h?.cpu||unknown),el('div','sub',h?.threads?((h.cores?h.cores+' 核 · ':'')+h.threads+' 线程'):''));
 memory.append(el('div','hardware-primary',h?.memory_total?bytes(h.memory_total):unknown),el('div','sub',h?.memory_available!==undefined?'可用 '+bytes(h.memory_available):''));
 const physical=h?.disks?.filter(d=>storageKind(d)==='disk')||[],volumes=h?.disks?.filter(d=>d.kind==='volume'||d.kind==='container')||[];
 if(h?.disks?.length){const b=el('button','disk-button',(physical.length?physical.length+' 块磁盘':'卷信息')+' ↗');b.type='button';b.setAttribute('aria-label',label+'：查看全部磁盘与卷');b.onclick=()=>showHardware(h,label);const available=freeSpace(h);disks.append(b,el('div','sub disk-remaining',available.known?'卷剩余 '+bytes(available.free):'剩余空间未获取'));b.textContent=(physical.length?physical.length+' 盘 · '+bytes(physical.reduce((n,d)=>n+(d.total||0),0)):'查看全部卷')+' ↗';}else disks.append(el('span','sub',h?.status==='unavailable'?'检测未成功':unknown));
 for(const c of [system,cpu,memory,disks]){if(h?.checked_at){const stale=Date.now()-h.checked_at>15*60_000;c.title='检测于 '+new Date(h.checked_at).toLocaleString()+(stale?' · 历史数据':'')+(h.status==='partial'?' · 部分信息不可用':'');if(stale)c.classList.add('hardware-stale');}else c.title=locked?'硬件详情已端到端加密，请先解锁服务器保险库。':'运行新版设备代理，或下发服务器检测。';}
 if(h?.checked_at){const stamp=system.querySelector('.sub');stamp.classList.add('hardware-stamp');stamp.textContent=[h.arch,h.refresh_failed?'刷新未成功':Date.now()-h.checked_at>15*60_000?'历史检测':h.status==='partial'?'部分检测':''].filter(Boolean).join(' · ');}
 return [system,cpu,memory,disks];
}
export function closeHardware(){document.querySelectorAll('.hardware-dialog').forEach(d=>{d.close();d.remove();});}
function showHardware(h,label){
 const d=el('dialog','hardware-dialog'),head=el('div','modal-head'),title=el('h2','',label+' · 存储'),close=el('button','close','×');title.id='hardware-title';d.setAttribute('aria-labelledby',title.id);close.setAttribute('aria-label','关闭存储详情');close.onclick=()=>d.close();head.append(title,close);const body=el('div','modal-body');const space=freeSpace(h);body.append(el('p','storage-summary',space.known?'已获取卷剩余 '+bytes(space.free)+' / '+bytes(space.total):'剩余空间未获取'));body.append(el('p','tip','检测于 '+new Date(h.checked_at).toLocaleString()+'。磁盘、分区与共享卷分开列出，容量不重复相加。内存盘、启动区和未连接块设备不计入磁盘总数。剩余空间为已获取文件系统/共享容器的可用空间，不含磁盘未分配空间。'));
 for(const [name,list] of [['磁盘',h.disks.filter(x=>storageKind(x)==='disk')],['分区、映射与卷',h.disks.filter(x=>!['disk','memory-device','boot-region','disconnected'].includes(storageKind(x)))],['其他块设备',h.disks.filter(x=>['memory-device','boot-region','disconnected'].includes(storageKind(x)))]]){body.append(el('h3','disk-heading',name+' · '+list.length));if(!list.length)body.append(el('p','tip','未获取此类信息'));for(const disk of list){const row=el('div','disk-detail'),top=el('div','disk-detail-head');top.append(el('strong','',disk.id),el('span','tag',kinds[storageKind(disk)]||disk.kind));row.append(top);if(disk.model)row.append(el('div','',disk.model));row.append(el('div','disk-facts',(disk.total?bytes(disk.total):'容量未知')+(disk.free!==undefined?' · 可用 '+bytes(disk.free):'')+(disk.filesystem?' · '+disk.filesystem:'')));if(disk.parent)row.append(el('div','sub','所属 '+disk.parent));if(disk.mounts?.length)row.append(el('div','disk-mounts',disk.mounts.join(' · ')));body.append(row);}}
 if(h.notes?.length)body.append(el('p','tip','部分信息因系统工具、权限或采集上限未能获取。'));d.append(head,body);document.body.append(d);d.onclose=()=>d.remove();d.showModal();
}
